// # ======================================================== #
// #                  ****WARNING****
// # This file is auto-generated!  Do NOT edit this file.
// # Profile Version = 21.115.00
// # Generated Date = 2023-11-18 12:40:14
// # ======================================================== #
pub const VERSION: &str = "21.115.00";
